version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repsydb
    ports:
    - "5432:5432"
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      -  "9000:9000"
      -  "9001:9001"
    command: server /data --console-address ":9001"
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      STORAGE_STRATEGY: file-system
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres